import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Satar',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'H-Hyde-DB-HC-221',
      slug: 'H-Hyde-DB-HC-221',
      category: 'Coats',
      image: '/images/H-Hyde-DB-HC-221.jpg', // 679px × 829px
      price: 431,
      countInStock: 10,
      brand: 'BOSS',
      rating: 4.7,
      numReviews: 22,
      description: 'high quality coat',
    },
    {
      // _id: '2',
      name: 'MAlancaster 3',
      slug: 'MAlancaster-3',
      category: 'Coats',
      image: '/images/MAlancaster3.jpg',
      price: 166,
      countInStock: 20,
      brand: 'BOSS',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Wolger Compact Melton',
      slug: 'Wolger-Compact-Melton',
      category: 'Coats',
      image: '/images/Wolger-Compact-Melton.jpg',
      price: 250,
      countInStock: 4,
      brand: 'BOSS',
      rating: 4.4,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'BELTED HERRINGBONE COAT',
      slug: 'BELTED-HERRINGBONE-COAT',
      category: 'Coats',
      image: '/images/BELTED-HERRINGBONE-COAT.jpg',
      price: 290,
      countInStock: 0,
      brand: 'BOSS',
      rating: 4.5,
      numReviews: 36,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Winsir Wool Coat',
      slug: 'Winsir-Wool-Coat',
      category: 'Coats',
      image: '/images/Winsir-Wool-Coat.jpg',
      price: 292,
      countInStock: 8,
      brand: 'BOSS',
      rating: 4.3,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Cashmere Coat',
      slug: 'Cashmere-Coat',
      category: 'Pants',
      image: '/images/Cashmere-Coat.jpg',
      price: 230,
      countInStock: 6,
      brand: 'BOSS',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
